version: '3.3'
services:
  backend:
    build: ./../backend
    env_file: 
      - ./../backend/.env
    volumes:
      - ./../backend:/backend
    working_dir: /backend
    ports:
      - '5000:5000'
    command: sh start.sh

  frontend:
    build: ./../frontend
    volumes:
      - ./../frontend:/frontend
    working_dir: /frontend
    ports:
      - '3000:3000'
    command: sh start.sh

  
     